### ISSUE TITLE
Submit

### ISSUE THREAD

**Issue by Polariche** [CGLAB-Classes/glskeleton#1]
96301286fa9a1d0a1b2232f96707143d9129685f

**Comment by cglab-gist-ta** [comment]
@Polariche  제출 검토는 완료했습니다. 
귀찮겠지만 혹시 커밋 해쉬를 여기가 아닌 학생 레포지토리(CGLAB-Classes/pa1-Polariche) 이슈보드에 남겨줄수 있나요?
